spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:carpediemdb
    username: sa
    password: sa
  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO