spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mariadb://carpediem-mariadb:3306/testdb
    username: user
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: 8080

logging:
  level:
    root: DEBUG